#!/bin/sh /etc/rc.common

START=20
STOP=15

start() {

    if ! pgrep pppwn > /dev/null; then

        interface=$(uci get pw.@params[0].interface)
        retry=$(uci get pw.@params[0].retry)
        sleep=$(uci get pw.@params[0].sleep)
        version=$(uci get pw.@params[0].version)
        stage1=$(uci get pw.@params[0].stage1)
        stage2=$(uci get pw.@params[0].stage2)
        timeout=$(uci get pw.@params[0].timeout)

        if pgrep pppoe-server > /dev/null; then
            /etc/init.d/pppoe-server stop
            sleep 3
        fi

        ip link set $interface down
        sleep 5
        ip link set $interface up

        if [ "$sleep" = "yes" ]; then
            sleep="--real-sleep"
        elif [ "$sleep" = "no" ]; then
            sleep=""
        fi
        if [ "$retry" = "yes" ]; then
            retry="--auto-retry"
        elif [ "$retry" = "no" ]; then
            retry=""
        fi

        result=$(pppwn --interface "$interface" --fw "$version" --stage1 "$stage1" --stage2 "$stage2" --timeout $timeout $sleep $retry)

        if [[ "$result" == *"\[\+\] Done\!"* ]]; then
            if ! pgrep pppoe-server > /dev/null; then
                /etc/init.d/pppoe-server start
                sleep 3
            fi
            exit 0
        else
            if ! pgrep pppoe-server > /dev/null; then
                /etc/init.d/pppoe-server start
                sleep 3
            fi
            exit 1
        fi

    fi

}

stop() {

    if ! pgrep pppoe-server > /dev/null; then
        /etc/init.d/pppoe-server start
        sleep 3
    fi

    interface=$(uci get pw.@params[0].interface)

    ip link set $interface down
    sleep 5
    ip link set $interface up

    pids=$(pgrep pppwn)
    
    for pid in $pids; do
        kill $pid
    done

}